env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - 'prettier'
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  
plugins:
  - react
  - '@typescript-eslint'
  - 'prettier'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  semi:
    - error
    - never
  react/react-in-jsx-scope: off
  react/display-name: off
  prettier/prettier: error
